services:
  # PHPアプリケーションサーバー
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html:cached
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro

  # Webサーバー（Nginx）
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html:cached
    depends_on:
      - php

  # データベースサーバー（MySQL）
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: posse
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  # PHPMyAdmin（データベース管理ツール）
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_ABSOLUTE_URI: http://localhost:8081/
    ports:
      - "8081:80"
    depends_on:
      - db

  # メール確認用サーバー（MailHog）
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"  # Web UI
      - "1025:1025"  # SMTP

# ボリューム設定
volumes:
  mysql-data:
